// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GamePhase } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { KnockOutEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED, DISCARD_TOP_X_CARDS_FROM_YOUR_DECK } from '../../game/store/prefabs/prefabs';

export class MegaSableyeAndTyranitarGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 280;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C, C, C];

  private usedGreedyCrush = false;

  public attacks = [
    {
      name: 'Greedy Crush',
      cost: [D, D, D, D, C],
      damage: 210,
      text: 'If your opponent\'s Pokemon-GX or Pokemon-EX is Knocked Out by damage from this attack, take 1 more Prize card.'
    },
    {
      name: 'Gigafall-GX',
      cost: [D, D, D, D, C],
      damage: 250,
      text: 'If this Pokemon has at least 5 extra Energy attached to it (in addition to this attack\'s cost), discard the top 15 cards of your opponent\'s deck. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'UNM';
  public setNumber: string = '126';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mega Sableye & Tyranitar-GX';
  public fullName: string = 'Mega Sableye & Tyranitar-GX UNM';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Greedy Crush
    // Ref: set-unbroken-bonds/pheromosa-and-buzzwole-gx.ts (Beast Game-GX - extra prize on KO)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedGreedyCrush = true;
    }

    // Greedy Crush extra prize
    if (effect instanceof KnockOutEffect && effect.target === effect.player.active) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (state.phase !== GamePhase.ATTACK || state.players[state.activePlayer] !== opponent) {
        return state;
      }

      const pokemonCard = opponent.active.getPokemonCard();
      if (pokemonCard !== this) {
        return state;
      }

      if (this.usedGreedyCrush) {
        const targetCard = effect.target.getPokemonCard();
        if (targetCard && (targetCard.tags.includes(CardTag.POKEMON_GX) || targetCard.tags.includes(CardTag.POKEMON_EX))) {
          if (effect.prizeCount > 0) {
            effect.prizeCount += 1;
          }
        }
        this.usedGreedyCrush = false;
      }
    }

    // Attack 2: Gigafall-GX
    // Ref: set-unbroken-bonds/rhydon.ts (Dirty Work - DISCARD_TOP_X_CARDS_FROM_YOUR_DECK)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      // Check if this Pokemon has at least 5 extra energy (total 10 energy: 5 cost + 5 extra)
      const extraEffectCost: CardType[] = [D, D, D, D, C, C, C, C, C, C];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (meetsExtraEffectCost) {
        DISCARD_TOP_X_CARDS_FROM_YOUR_DECK(store, state, opponent, 15, this, effect);
      }
    }

    // Cleanup boolean flag
    if (effect instanceof EndTurnEffect) {
      this.usedGreedyCrush = false;
    }

    return state;
  }
}
