// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType } from '../../game/store/card/card-types';
import { AttachEnergyPrompt, Card, CardTarget, ChooseCardsPrompt, GameMessage, PlayerType, PokemonCardList, SlotType, StoreLike, State, StateUtils } from '../../game';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class GreninjaAndZoroarkGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 250;
  public weakness = [{ type: F }];
  public resistance = [{ type: P, value: -20 }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Dark Pulse',
      cost: [D, C],
      damage: 30,
      damageCalculation: '+' as '+',
      text: 'This attack does 30 more damage times the amount of [D] Energy attached to all of your Pokémon.'
    },
    {
      name: 'Dark Union-GX',
      cost: [D, C],
      damage: 0,
      text: 'Put 2 in any combination of Darkness Pokémon-GX and Darkness Pokémon-EX from your discard pile onto your Bench. If this Pokémon has at least 1 extra Energy attached to it (in addition to this attack\'s cost), attach 2 Energy cards from your discard pile to each Pokémon that you put onto your Bench in this way. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '107';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Greninja & Zoroark-GX';
  public fullName: string = 'Greninja & Zoroark-GX UNB';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Dark Pulse
    // Ref: set-breakpoint/darkrai-ex.ts (Dark Pulse - count D energy across all Pokemon)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      let darkEnergyCount = 0;
      player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
        const checkEnergy = new CheckProvidedEnergyEffect(player, cardList);
        store.reduceEffect(state, checkEnergy);
        checkEnergy.energyMap.forEach(em => {
          darkEnergyCount += em.provides.filter(t => t === CardType.DARK).length;
        });
      });

      effect.damage += 30 * darkEnergyCount;
    }

    // Attack 2: Dark Union-GX
    // Ref: set-burning-shadows/ho-oh-gx.ts (Eternal Flame-GX - put Pokemon from discard to bench), set-unbroken-bonds/greninja-zoroark-gx.ts (existing implementation)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      const slots: PokemonCardList[] = player.bench.filter(b => b.cards.length === 0);
      if (slots.length === 0) {
        return state;
      }

      // Filter for Darkness GX/EX Pokemon in discard
      const blocked: number[] = [];
      player.discard.cards.forEach((card, index) => {
        if (!(card instanceof PokemonCard) ||
          card.cardType !== CardType.DARK ||
          (!card.tags.includes(CardTag.POKEMON_GX) && !card.tags.includes(CardTag.POKEMON_EX))) {
          blocked.push(index);
        }
      });

      const maxPut = Math.min(2, slots.length);
      let placedCards: Card[] = [];

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_PUT_ONTO_BENCH,
        player.discard,
        { superType: SuperType.POKEMON },
        { min: 0, max: maxPut, allowCancel: false, blocked }
      ), selected => {
        placedCards = selected || [];

        if (placedCards.length === 0) {
          return;
        }

        placedCards.forEach((card, index) => {
          if (index < slots.length) {
            player.discard.moveCardTo(card, slots[index]);
            slots[index].pokemonPlayedTurn = state.turn;
          }
        });
      });

      // Check for extra energy (at least 1 extra beyond the [D, C] cost)
      const extraEffectCost: CardType[] = [D, C, C];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (!meetsExtraEffectCost || placedCards.length === 0) {
        return state;
      }

      // Attach 2 Energy cards from discard to each Pokemon placed on bench
      const blockedTo: CardTarget[] = [];
      player.bench.forEach((bench, index) => {
        if (bench.cards.length === 0) {
          blockedTo.push({ player: PlayerType.BOTTOM_PLAYER, slot: SlotType.BENCH, index });
          return;
        }
        // Only allow attaching to Pokemon we just placed
        const pokemonCard = bench.getPokemonCard();
        if (!pokemonCard || !placedCards.includes(pokemonCard)) {
          blockedTo.push({ player: PlayerType.BOTTOM_PLAYER, slot: SlotType.BENCH, index });
        }
      });

      const totalAttach = placedCards.length * 2;

      store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_CARDS,
        player.discard,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH],
        { superType: SuperType.ENERGY },
        { allowCancel: false, min: 0, max: totalAttach, blockedTo }
      ), transfers => {
        transfers = transfers || [];
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          player.discard.moveCardTo(transfer.card, target);
        }
      });
    }

    return state;
  }
}
