// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GamePhase } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { KnockOutEffect } from '../../game/store/effects/game-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED, NEXT_TURN_ATTACK_BASE_DAMAGE } from '../../game/store/prefabs/prefabs';
import { THIS_ATTACK_DOES_X_DAMAGE_TO_1_OF_YOUR_OPPONENTS_BENCHED_POKEMON } from '../../game/store/prefabs/attack-effects';

export class PheromosaAndBuzzwoleGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX, CardTag.ULTRA_BEAST];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = G;
  public hp: number = 260;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Jet Punch',
      cost: [G],
      damage: 30,
      text: 'This attack does 30 damage to 1 of your opponent\'s Benched Pokémon. (Don\'t apply Weakness and Resistance for Benched Pokémon.)'
    },
    {
      name: 'Elegant Sole',
      cost: [G, G, C],
      damage: 190,
      text: 'During your next turn, this Pokémon\'s Elegant Sole attack\'s base damage is 60.'
    },
    {
      name: 'Beast Game-GX',
      cost: [G],
      damage: 50,
      text: 'If your opponent\'s Pokémon is Knocked Out by damage from this attack, take 1 more Prize card. If this Pokémon has at least 7 extra Energy attached to it (in addition to this attack\'s cost), take 3 more Prize cards instead. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'UNB';
  public setNumber: string = '1';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Pheromosa & Buzzwole-GX';
  public fullName: string = 'Pheromosa & Buzzwole-GX UNB';

  public readonly ELEGANT_SOLE_MARKER = 'PHERO_BUZZ_ELEGANT_SOLE_MARKER';
  public readonly ELEGANT_SOLE_CLEAR_MARKER = 'PHERO_BUZZ_ELEGANT_SOLE_CLEAR_MARKER';

  private usedBeastGame = false;
  private usedEnhancedBeastGame = false;

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Jet Punch
    // Ref: set-unbroken-bonds/pheromosa-buzzwole-gx.ts (Jet Punch)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      this.usedBeastGame = false;
      this.usedEnhancedBeastGame = false;

      THIS_ATTACK_DOES_X_DAMAGE_TO_1_OF_YOUR_OPPONENTS_BENCHED_POKEMON(30, effect, store, state);
    }

    // Attack 2: Elegant Sole
    // Ref: set-unbroken-bonds/pheromosa-buzzwole-gx.ts (Elegant Sole), set-unbroken-bonds/cubone.ts (NEXT_TURN_ATTACK_BASE_DAMAGE)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      this.usedBeastGame = false;
      this.usedEnhancedBeastGame = false;
    }

    NEXT_TURN_ATTACK_BASE_DAMAGE(effect, {
      setupAttack: this.attacks[1],
      boostedAttack: this.attacks[1],
      source: this,
      baseDamage: 60,
      bonusMarker: this.ELEGANT_SOLE_MARKER,
      clearMarker: this.ELEGANT_SOLE_CLEAR_MARKER
    });

    // Attack 3: Beast Game-GX
    // Ref: set-unbroken-bonds/pheromosa-buzzwole-gx.ts (Beast Game-GX)
    if (WAS_ATTACK_USED(effect, 2, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      this.usedBeastGame = true;

      // Check if this Pokemon has at least 7 extra Energy (total 8 = 1 cost + 7 extra)
      const extraEffectCost: CardType[] = [G, C, C, C, C, C, C, C];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (meetsExtraEffectCost) {
        this.usedEnhancedBeastGame = true;
      }
    }

    // Beast Game extra prizes
    if (effect instanceof KnockOutEffect && effect.target === effect.player.active) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (state.phase !== GamePhase.ATTACK || state.players[state.activePlayer] !== opponent) {
        return state;
      }

      const pokemonCard = opponent.active.getPokemonCard();
      if (pokemonCard !== this) {
        return state;
      }

      if (this.usedBeastGame) {
        if (effect.prizeCount > 0) {
          effect.prizeCount += 1;
          this.usedBeastGame = false;

          if (this.usedEnhancedBeastGame) {
            effect.prizeCount += 2;
            this.usedEnhancedBeastGame = false;
          }
        }
      }
    }

    return state;
  }
}
