// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, EnergyType, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, AttachEnergyPrompt, GameMessage, PlayerType, ShuffleDeckPrompt, SlotType, StateUtils, GamePhase } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AttackEffect, KnockOutEffect } from '../../game/store/effects/game-effects';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';

function* useUltimateRay(next: Function, store: StoreLike, state: State,
  effect: AttackEffect): IterableIterator<State> {

  const player = effect.player;

  if (player.deck.cards.length === 0) {
    return state;
  }

  yield store.prompt(state, new AttachEnergyPrompt(
    player.id,
    GameMessage.ATTACH_ENERGY_TO_BENCH,
    player.deck,
    PlayerType.BOTTOM_PLAYER,
    [SlotType.BENCH, SlotType.ACTIVE],
    { superType: SuperType.ENERGY, energyType: EnergyType.BASIC },
    { allowCancel: false, min: 0, max: 3 }
  ), transfers => {
    transfers = transfers || [];
    for (const transfer of transfers) {
      const target = StateUtils.getTarget(state, player, transfer.to);
      player.deck.moveCardTo(transfer.card, target);
      next();
    }
  });

  return store.prompt(state, new ShuffleDeckPrompt(player.id), order => {
    player.deck.applyOrder(order);
  });
}

export class ArceusAndDialgaAndPalkiaGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = N;
  public hp: number = 280;
  public weakness = [{ type: Y }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Ultimate Ray',
      cost: [W, M, C],
      damage: 150,
      text: 'Search your deck for up to 3 basic Energy cards and attach them to your Pokémon in any way you like. Then, shuffle your deck.'
    },
    {
      name: 'Altered Creation-GX',
      cost: [M],
      damage: 0,
      text: 'For the rest of this game, your Pokémon\'s attacks do 30 more damage to your opponent\'s Active Pokémon (before applying Weakness and Resistance). If this Pokémon has at least 1 extra [W] Energy attached to it (in addition to this attack\'s cost), when your opponent\'s Active Pokémon is Knocked Out by damage from those attacks, take 1 more Prize card. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '156';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Arceus & Dialga & Palkia-GX';
  public fullName: string = 'Arceus & Dialga & Palkia-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Ultimate Ray
    // Ref: set-cosmic-eclipse/arceus-dialga-palkia-gx.ts (Ultimate Ray)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const generator = useUltimateRay(() => generator.next(), store, state, effect as AttackEffect);
      return generator.next().value;
    }

    // Attack 2: Altered Creation-GX
    // Ref: set-cosmic-eclipse/arceus-dialga-palkia-gx.ts (Altered Creation-GX)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;
      player.alteredCreationDamage = true;

      // Check attached energy
      const checkEnergy = new CheckProvidedEnergyEffect(player, player.active);
      state = store.reduceEffect(state, checkEnergy);

      // Count Water energies attached
      const waterEnergies = checkEnergy.energyMap.filter(e =>
        e.provides.includes(CardType.WATER) || e.provides.includes(CardType.ANY)
      );

      // Check if there's at least 1 extra Water energy beyond the Metal cost
      if (waterEnergies.length >= 1) {
        player.usedAlteredCreation = true;
      }
    }

    // Apply +30 damage boost
    if (effect instanceof DealDamageEffect) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (player.alteredCreationDamage === true && effect.target === opponent.active && !effect.damageIncreased) {
        effect.damage += 30;
        effect.damageIncreased = true;
      }
    }

    if (effect instanceof KnockOutEffect) {
      const knockedOutOwner = effect.player;
      const attacker = StateUtils.getOpponent(state, knockedOutOwner);

      if (effect.target === knockedOutOwner.active &&
        state.phase === GamePhase.ATTACK &&
        state.players[state.activePlayer] === attacker &&
        attacker.usedAlteredCreation === true &&
        !effect.prizeIncreased) {
        effect.prizeCount += 1;
        effect.prizeIncreased = true;
      }
    }

    return state;
  }
}
