// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, EnergyType, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, EnergyCard, AttachEnergyPrompt, PokemonCardList } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { HealEffect } from '../../game/store/effects/game-effects';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED } from '../../game/store/prefabs/attack-effects';

export class BlastoiseAndPiplupGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 270;
  public weakness = [{ type: G }];
  public retreat = [C, C, C];

  public attacks = [
    {
      name: 'Splash Maker',
      cost: [W, W, C],
      damage: 150,
      text: 'You may attach up to 3 [W] Energy cards from your hand to your Pokémon in any way you like. If you do, heal 50 damage from those Pokémon for each card you attached to them in this way.'
    },
    {
      name: 'Bubble Launcher-GX',
      cost: [W, W, C],
      damage: 100,
      damageCalculation: '+' as '+',
      text: 'Your opponent\'s Active Pokémon is now Paralyzed. If this Pokémon has at least 3 extra [W] Energy attached to it (in addition to this attack\'s cost), this attack does 150 more damage. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '38';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Blastoise & Piplup-GX';
  public fullName: string = 'Blastoise & Piplup-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Splash Maker
    // Refs: set-unbroken-bonds/blastoise-gx.ts (Giant Geyser-GX - attach Water from hand), set-crimson-invasion/miltank.ts (Moomoo Malt - heal on attach)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      const hasWaterEnergy = player.hand.cards.some(c =>
        c instanceof EnergyCard && c.energyType === EnergyType.BASIC && c.provides.includes(CardType.WATER)
      );

      if (!hasWaterEnergy) {
        return state;
      }

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_CARDS,
        player.hand,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Water Energy' },
        { allowCancel: true, min: 0, max: 3 }
      ), transfers => {
        transfers = transfers || [];
        if (transfers.length === 0) {
          return;
        }

        // Track how many cards attached to each target
        const healMap = new Map<PokemonCardList, number>();
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          player.hand.moveCardTo(transfer.card, target);
          healMap.set(target, (healMap.get(target) || 0) + 1);
        }

        // Heal 50 per card attached to each Pokemon
        healMap.forEach((count, target) => {
          const healEffect = new HealEffect(player, target, 50 * count);
          store.reduceEffect(state, healEffect);
        });
      });
    }

    // Attack 2: Bubble Launcher-GX
    // Refs: set-team-up/eevee-and-snorlax-gx.ts (Megaton Friends-GX - extra energy check), set-lost-thunder/alolan-ninetales-gx.ts (Sublimation-GX - GX attack pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_PARALYZED(store, state, effect);

      // Check for 3 extra [W] Energy (cost is [W, W, C], so need [W, W, C, W, W, W])
      const extraEffectCost: CardType[] = [CardType.WATER, CardType.WATER, CardType.COLORLESS, CardType.WATER, CardType.WATER, CardType.WATER];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (meetsExtraEffectCost) {
        effect.damage += 150;
      }
    }

    return state;
  }
}
