// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType } from '../../game';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP, THIS_ATTACK_DOES_X_DAMAGE_TO_1_OF_YOUR_OPPONENTS_BENCHED_POKEMON } from '../../game/store/prefabs/attack-effects';

export class MegaLopunnyAndJigglypuffGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = C;
  public hp: number = 240;
  public weakness = [{ type: F }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Jumping Balloon',
      cost: [C, C, C],
      damage: 60,
      damageCalculation: '+' as '+',
      text: 'This attack does 60 more damage for each of your opponent\'s Pokémon-GX and Pokémon-EX in play.'
    },
    {
      name: 'Puffy Smashers-GX',
      cost: [C],
      damage: 0,
      text: 'Your opponent\'s Active Pokémon is now Asleep. If this Pokémon has at least 4 extra Energy attached to it (in addition to this attack\'s cost), this attack does 200 damage to 1 of your opponent\'s Benched Pokémon. (Don\'t apply Weakness and Resistance for Benched Pokémon.) (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '165';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Mega Lopunny & Jigglypuff-GX';
  public fullName: string = 'Mega Lopunny & Jigglypuff-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Jumping Balloon
    // Ref: set-cosmic-eclipse/heliolisk.ts (Parabolic Counter - count opponent's Pokemon of type)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      let gxExCount = 0;
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList) => {
        const pokemonCard = cardList.getPokemonCard();
        if (pokemonCard && (pokemonCard.tags.includes(CardTag.POKEMON_GX) || pokemonCard.tags.includes(CardTag.POKEMON_EX))) {
          gxExCount++;
        }
      });

      effect.damage += 60 * gxExCount;
    }

    // Attack 2: Puffy Smashers-GX
    // Refs: set-unbroken-bonds/pheromosa-and-buzzwole-gx.ts (Beast Game-GX - extra energy check), set-hidden-fates/nihilego-gx.ts (GX attack pattern)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      // Always apply Asleep
      YOUR_OPPPONENTS_ACTIVE_POKEMON_IS_NOW_ASLEEP(store, state, effect);

      // Check for 4 extra energy (total 5 = 1 cost + 4 extra)
      const extraEffectCost: CardType[] = [C, C, C, C, C];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (meetsExtraEffectCost) {
        THIS_ATTACK_DOES_X_DAMAGE_TO_1_OF_YOUR_OPPONENTS_BENCHED_POKEMON(200, effect, store, state);
      }
    }

    return state;
  }
}
