// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, GameError, GameMessage, PokemonCardList, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { HealEffect } from '../../game/store/effects/game-effects';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { ChooseCardsPrompt } from '../../game/store/prompts/choose-cards-prompt';
import { WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN, BLOCK_IF_GX_ATTACK_USED, MOVE_CARDS, TAKE_X_PRIZES } from '../../game/store/prefabs/prefabs';

export class NaganadelAndGuzzlordGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX, CardTag.ULTRA_BEAST];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = N;
  public hp: number = 280;
  public weakness = [{ type: Y }];
  public retreat = [C, C, C];

  public readonly VIOLENT_APPETITE_MARKER = 'NAGANADEL_GUZZLORD_GX_CEC_VIOLENT_APPETITE_MARKER';

  public powers = [  {
    name: 'Violent Appetite',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn (before your attack), you may discard a Pokémon from your hand. If you do, heal 60 damage from this Pokémon.'
  }];

  public attacks = [
    {
      name: 'Jet Pierce',
      cost: [P, D, C],
      damage: 180,
      text: ''
    },
    {
      name: 'Chaotic Order-GX',
      cost: [C],
      damage: 0,
      text: 'Turn all of your Prize cards face up. (Those Prize cards remain face up for the rest of the game.) If this Pokémon has at least 1 extra [P] Energy and 1 extra [D] Energy attached to it (in addition to this attack\'s cost), take 2 Prize cards. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '158';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Naganadel & Guzzlord-GX';
  public fullName: string = 'Naganadel & Guzzlord-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Violent Appetite
    // Ref: set-unbroken-bonds/melmetal.ts (Metal Eater - discard Pokemon from hand to heal)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      // Check for Pokemon in hand
      const hasPokemon = player.hand.cards.some(c => c instanceof PokemonCard);

      if (!hasPokemon) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.VIOLENT_APPETITE_MARKER, this);
      ABILITY_USED(player, this);

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        { superType: SuperType.POKEMON },
        { allowCancel: false, min: 1, max: 1 }
      ), cards => {
        const selected = cards || [];
        if (selected.length > 0) {
          MOVE_CARDS(store, state, player.hand, player.discard, { cards: selected });

          // Heal 60 damage from this Pokemon
          const cardList = StateUtils.findCardList(state, this) as PokemonCardList;
          const healEffect = new HealEffect(player, cardList, 60);
          store.reduceEffect(state, healEffect);
        }
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.VIOLENT_APPETITE_MARKER, this);

    // Attack 2: Chaotic Order-GX
    // Refs: set-team-rocket/here-comes-team-rocket.ts (prize face up pattern), set-team-up/eevee-and-snorlax-gx.ts (extra energy check for GX)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;

      // Turn all prize cards face up
      player.prizes.forEach((prize) => {
        if (!prize.faceUpPrize) {
          prize.faceUpPrize = true;
          prize.isSecret = false;
          prize.isPublic = true;
        }
      });

      // Check for extra [P] and [D] energy (cost is [C], so need [C, P, D])
      const extraEffectCost: CardType[] = [CardType.COLORLESS, CardType.PSYCHIC, CardType.DARK];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (meetsExtraEffectCost) {
        TAKE_X_PRIZES(store, state, player, 2);
      }
    }

    return state;
  }
}
