// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, PlayerType, ShuffleDeckPrompt } from '../../game';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { WAS_ATTACK_USED, BLOCK_IF_GX_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { FLIP_A_COIN_UNTIL_YOU_GET_TAILS_DO_X_MORE_DAMAGE_PER_HEADS } from '../../game/store/prefabs/attack-effects';

export class TogepiAndCleffaAndIgglybuffGx extends PokemonCard {
  public tags = [CardTag.TAG_TEAM, CardTag.POKEMON_GX];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = Y;
  public hp: number = 240;
  public weakness = [{ type: M }];
  public resistance = [{ type: D, value: -20 }];
  public retreat = [C, C];

  public readonly SUPREME_PUFF_MARKER = 'TOGEPI_CLEFFA_IGGLYBUFF_SUPREME_PUFF_MARKER';
  public readonly SUPREME_PUFF_MARKER_2 = 'TOGEPI_CLEFFA_IGGLYBUFF_SUPREME_PUFF_MARKER_2';

  public attacks = [
    {
      name: 'Rolling Panic',
      cost: [Y, Y, C],
      damage: 120,
      damageCalculation: '+' as '+',
      text: 'Flip a coin until you get tails. This attack does 30 more damage for each heads.'
    },
    {
      name: 'Supreme Puff-GX',
      cost: [Y, Y],
      damage: 0,
      text: 'Take another turn after this one. (Skip the between-turns step.) If this Pokémon has at least 14 extra [Y] Energy attached to it (in addition to this attack\'s cost), your opponent shuffles all of their Benched Pokémon and all cards attached to them into their deck. (You can\'t use more than 1 GX attack in a game.)'
    }
  ];

  public set: string = 'CEC';
  public setNumber: string = '143';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Togepi & Cleffa & Igglybuff-GX';
  public fullName: string = 'Togepi & Cleffa & Igglybuff-GX CEC';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Turn skip cleanup (2-phase: first end turn marks phase 2, second end turn clears)
    // Ref: set-cosmic-eclipse/togepi-cleffa-igglybuff-gx.ts (Supreme Puff-GX)
    if (effect instanceof EndTurnEffect && effect.player.marker.hasMarker(this.SUPREME_PUFF_MARKER_2, this)) {
      effect.player.marker.removeMarker(this.SUPREME_PUFF_MARKER, this);
      effect.player.marker.removeMarker(this.SUPREME_PUFF_MARKER_2, this);
      effect.player.usedTurnSkip = false;
    }

    if (effect instanceof EndTurnEffect && effect.player.marker.hasMarker(this.SUPREME_PUFF_MARKER, this)) {
      effect.player.marker.addMarker(this.SUPREME_PUFF_MARKER_2, this);
    }

    // Attack 1: Rolling Panic
    // Ref: set-hidden-fates/kangaskhan.ts (flip until tails + more damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      return FLIP_A_COIN_UNTIL_YOU_GET_TAILS_DO_X_MORE_DAMAGE_PER_HEADS(store, state, effect, 30);
    }

    // Attack 2: Supreme Puff-GX
    // Ref: set-cosmic-eclipse/togepi-cleffa-igglybuff-gx.ts (Supreme Puff-GX - extra turn)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      BLOCK_IF_GX_ATTACK_USED(player);
      player.usedGX = true;
      player.marker.addMarker(this.SUPREME_PUFF_MARKER, this);
      player.usedTurnSkip = true;

      // Check for 14 extra Fairy energy (total 16 = 2 cost + 14 extra)
      const extraEffectCost: CardType[] = [Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, Y, Y];
      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      store.reduceEffect(state, checkProvidedEnergy);
      const meetsExtraEffectCost = StateUtils.checkEnoughEnergy(checkProvidedEnergy.energyMap, extraEffectCost);

      if (!meetsExtraEffectCost) {
        return state;
      }

      const opponent = StateUtils.getOpponent(state, player);

      // Shuffle all benched Pokemon and cards attached to them into deck
      opponent.forEachPokemon(PlayerType.TOP_PLAYER, (cardList, card) => {
        if (cardList !== opponent.active) {
          // Move tools first (moveTo doesn't handle tools)
          const tools = cardList.tools.slice();
          tools.forEach(t => { cardList.moveCardTo(t, opponent.deck); });
          cardList.moveTo(opponent.deck);
        }
      });

      store.prompt(state, new ShuffleDeckPrompt(opponent.id), order => {
        opponent.deck.applyOrder(order);
      });
    }

    return state;
  }
}
