// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { GameError, GameMessage, PowerType, StoreLike, State, StateUtils } from '../../game';
import { CardTarget, PlayerType, SlotType } from '../../game/store/actions/play-card-action';
import { Effect } from '../../game/store/effects/effect';
import { WAS_POWER_USED, COIN_FLIP_PROMPT, IS_ABILITY_BLOCKED, SWITCH_IN_OPPONENT_BENCHED_POKEMON, USE_ABILITY_ONCE_PER_TURN, ABILITY_USED, REMOVE_MARKER_AT_END_OF_TURN } from '../../game/store/prefabs/prefabs';

export class Appletun extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Applin';
  public cardType: CardType = G;
  public hp: number = 90;
  public weakness = [{ type: R }];
  public retreat = [C, C, C];

  public powers = [  {
    name: 'Delicious Aroma',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, you may flip a coin. If heads, switch 1 of your opponent\'s Benched Basic Pokémon with their Active Pokémon.'
  }];

  public attacks = [
    {
      name: 'Solar Beam',
      cost: [G, C],
      damage: 70,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV014';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Appletun';
  public fullName: string = 'Appletun SHF';

  public readonly DELICIOUS_AROMA_MARKER = 'APPLETUN_SHF_DELICIOUS_AROMA_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Delicious Aroma
    // Ref: set-rebel-clash/appletun.ts (IS_ABILITY_BLOCKED + USE_ABILITY_ONCE_PER_TURN + COIN_FLIP_PROMPT + gust)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      const opponent = StateUtils.getOpponent(state, player);

      const hasBasicBenched = opponent.bench.some(bench => {
        const card = bench.getPokemonCard();
        return card && card.stage === Stage.BASIC;
      });

      if (!hasBasicBenched) {
        throw new GameError(GameMessage.CANNOT_USE_POWER);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.DELICIOUS_AROMA_MARKER, this);
      ABILITY_USED(player, this);

      // Block non-Basic benched Pokemon slots
      const blocked: CardTarget[] = [];
      opponent.bench.forEach((bench, index) => {
        const pokemonCard = bench.getPokemonCard();
        if (!pokemonCard || pokemonCard.stage !== Stage.BASIC) {
          blocked.push({ player: PlayerType.TOP_PLAYER, slot: SlotType.BENCH, index });
        }
      });

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (result) {
          SWITCH_IN_OPPONENT_BENCHED_POKEMON(store, state, player, { blocked });
        }
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.DELICIOUS_AROMA_MARKER, this);

    return state;
  }
}
