// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PowerEffect } from '../../game/store/effects/game-effects';
import { AttachEnergyEffect } from '../../game/store/effects/play-card-effects';

export class Arctozolt extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Rare Fossil';
  public cardType: CardType = L;
  public hp: number = 130;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public powers = [  {
    name: 'Biting Whirlpool',
    powerType: PowerType.ABILITY,
    text: 'Whenever your opponent attaches an Energy card from their hand to 1 of their Pokémon, put 2 damage counters on that Pokémon.'
  }];

  public attacks = [
    {
      name: 'Electro Ball',
      cost: [L, C],
      damage: 70,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV046';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Arctozolt';
  public fullName: string = 'Arctozolt SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Biting Whirlpool (passive - damage when opponent attaches energy from hand)
    // Ref: set-darkness-ablaze/arctozolt.ts (AttachEnergyEffect + owner check + PowerEffect stub)
    if (effect instanceof AttachEnergyEffect) {
      const player = effect.player;

      // Find Arctozolt's owner; check that Arctozolt is actually in play and
      // that the attaching player is the opponent (not Arctozolt's owner)
      const cardList = StateUtils.findCardList(state, this);
      const owner = StateUtils.findOwner(state, cardList);

      // Must be in play (active or bench) for owner, not in hand/deck/discard
      if (!StateUtils.isPokemonInPlay(owner, this)) {
        return state;
      }

      // Only trigger when opponent attaches, not when owner attaches
      if (owner === player) {
        return state;
      }

      // Try to reduce PowerEffect, to check if something is blocking our ability
      try {
        const stub = new PowerEffect(owner, {
          name: 'test',
          powerType: PowerType.ABILITY,
          text: ''
        }, this);
        store.reduceEffect(state, stub);
      } catch {
        return state;
      }

      effect.target.damage += 20;
    }

    return state;
  }
}
