// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../game/store/card/card-types';
import { StoreLike, State, ChooseCardsPrompt, GameMessage } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';

export class Barraskewda extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Arrokuda';
  public cardType: CardType = W;
  public hp: number = 120;
  public weakness = [{ type: L }];
  public retreat = [C];

  public attacks = [
    {
      name: 'Peck',
      cost: [C],
      damage: 30,
      text: ''
    },
    {
      name: 'Spiral Jet',
      cost: [W],
      damage: 130,
      text: 'Discard 2 [W] Energy cards from your hand. If you don\'t, this attack does nothing.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV032';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Barraskewda';
  public fullName: string = 'Barraskewda SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 2: Spiral Jet
    // Ref: set-rebel-clash/barraskewda.ts (Spiral Jet)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;

      let numberOfEnergy = 0;
      player.hand.cards.forEach(card => {
        if (card.superType === SuperType.ENERGY && card.energyType === EnergyType.BASIC && card.name === 'Water Energy') {
          numberOfEnergy++;
        }
      });

      if (numberOfEnergy < 2) {
        effect.damage = 0;
        return state;
      }

      state = store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Water Energy' },
        { allowCancel: false, min: 2, max: 2 }
      ), cards => {
        cards = cards || [];
        player.hand.moveCardsTo(cards, player.discard);
      });
    }

    return state;
  }
}
