// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, EnergyType, SuperType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, AttachEnergyPrompt, Card, ChooseEnergyPrompt, EnergyCard, GameMessage, PlayerType, SlotType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { AttackEffect, PowerEffect } from '../../game/store/effects/game-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';
import { CheckProvidedEnergyEffect } from '../../game/store/effects/check-effects';
import { DiscardCardsEffect } from '../../game/store/effects/attack-effects';

export class Cinderace extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Raboot';
  public cardType: CardType = R;
  public hp: number = 170;
  public weakness = [{ type: W }];
  public retreat = [C];

  public powers = [  {
    name: 'Libero',
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, when this Pokémon moves from your Bench to the Active Spot, you may attach up to 2 [R] Energy cards from your discard pile to it.'
  }];

  public attacks = [
    {
      name: 'Flare Striker',
      cost: [R, R, C],
      damage: 190,
      text: 'Discard 2 Energy from this Pokémon.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV017';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Cinderace';
  public fullName: string = 'Cinderace SHF';

  public readonly LIBERO_MARKER = 'CINDERACE_SHF_LIBERO_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Libero (triggered when moved from bench to active)
    // Ref: set-sword-and-shield/cinderace.ts (movedToActiveThisTurn + AttachEnergyPrompt from discard)
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = state.players[state.activePlayer];
      player.marker.removeMarker(this.LIBERO_MARKER, this);
    }

    const cardList = StateUtils.findCardList(state, this);
    const owner = StateUtils.findOwner(state, cardList);
    const player = state.players[state.activePlayer];

    if (effect instanceof EndTurnEffect) {
      this.movedToActiveThisTurn = false;
      player.marker.removeMarker(this.LIBERO_MARKER, this);
    }

    if (player === owner && !player.marker.hasMarker(this.LIBERO_MARKER, this)) {
      if (this.movedToActiveThisTurn === true) {
        player.marker.addMarker(this.LIBERO_MARKER, this);

        // Check if ability is blocked
        try {
          const stub = new PowerEffect(player, {
            name: 'test',
            powerType: PowerType.ABILITY,
            text: ''
          }, this);
          store.reduceEffect(state, stub);
        } catch {
          return state;
        }

        // Check if there are Fire Energy in discard
        const hasFireInDiscard = player.discard.cards.some(c => {
          return c instanceof EnergyCard
            && c.energyType === EnergyType.BASIC
            && c.provides.includes(CardType.FIRE);
        });

        if (!hasFireInDiscard) {
          return state;
        }

        return store.prompt(state, new AttachEnergyPrompt(
          player.id,
          GameMessage.ATTACH_ENERGY_TO_BENCH,
          player.discard,
          PlayerType.BOTTOM_PLAYER,
          [SlotType.ACTIVE],
          { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Fire Energy' },
          { allowCancel: true, min: 0, max: 2 }
        ), transfers => {
          transfers = transfers || [];
          if (transfers.length === 0) {
            return;
          }
          for (const transfer of transfers) {
            const target = StateUtils.getTarget(state, player, transfer.to);
            player.discard.moveCardTo(transfer.card, target);
          }
        });
      }
    }

    // Attack 1: Flare Striker
    // Ref: set-sword-and-shield/cinderace.ts (ChooseEnergyPrompt + DiscardCardsEffect)
    if (effect instanceof AttackEffect && effect.attack === this.attacks[0]) {
      const player = effect.player;

      const checkProvidedEnergy = new CheckProvidedEnergyEffect(player);
      state = store.reduceEffect(state, checkProvidedEnergy);

      state = store.prompt(state, new ChooseEnergyPrompt(
        player.id,
        GameMessage.CHOOSE_ENERGIES_TO_DISCARD,
        checkProvidedEnergy.energyMap,
        [C, C],
        { allowCancel: false }
      ), energy => {
        const cards: Card[] = (energy || []).map(e => e.card);
        const discardEnergy = new DiscardCardsEffect(effect, cards);
        discardEnergy.target = player.active;
        store.reduceEffect(state, discardEnergy);
      });
    }

    return state;
  }
}
