// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, BoardEffect } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, ConfirmPrompt, GameMessage, PlayerType, StateUtils } from '../../game';
import { PowerEffect } from '../../game/store/effects/game-effects';
import { Effect } from '../../game/store/effects/effect';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';
import { AFTER_ATTACK, DRAW_CARDS_UNTIL_CARDS_IN_HAND, ADD_POISON_TO_PLAYER_ACTIVE } from '../../game/store/prefabs/prefabs';

export class CrobatV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 180;
  public weakness = [{ type: F }];
  public retreat = [C];

  public powers = [  {
    name: 'Dark Asset',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand onto your Bench during your turn, you may draw cards until you have 6 cards in your hand. You can\'t use more than 1 Dark Asset Ability each turn.'
  }];

  public attacks = [
    {
      name: 'Venomous Fang',
      cost: [D, C],
      damage: 70,
      text: 'Your opponent\'s Active Pokémon is now Poisoned.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = '44';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Crobat V';
  public fullName: string = 'Crobat V SHF';

  public readonly DARK_ASSET_MARKER = 'CROBAT_V_SHF_DARK_ASSET_MARKER';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Dark Asset
    // Ref: set-darkness-ablaze/crobat-v.ts (PlayPokemonEffect + ConfirmPrompt + draw to 6 + once-per-turn marker)
    if (effect instanceof EndTurnEffect && effect.player.marker.hasMarker(this.DARK_ASSET_MARKER, this)) {
      const player = effect.player;
      player.marker.removeMarker(this.DARK_ASSET_MARKER, this);
    }

    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = effect.player;
      if (player.marker.hasMarker(this.DARK_ASSET_MARKER, this)) {
        return state;
      }

      // Try to reduce PowerEffect, to check if something is blocking our ability
      try {
        const stub = new PowerEffect(player, {
          name: 'test',
          powerType: PowerType.ABILITY,
          text: ''
        }, this);
        store.reduceEffect(state, stub);
      } catch {
        return state;
      }

      if (player.hand.cards.length > 6) {
        return state;
      }

      state = store.prompt(state, new ConfirmPrompt(
        effect.player.id,
        GameMessage.WANT_TO_USE_ABILITY,
      ), wantToUse => {
        if (wantToUse) {
          player.marker.addMarker(this.DARK_ASSET_MARKER, this);

          player.forEachPokemon(PlayerType.BOTTOM_PLAYER, cardList => {
            if (cardList.getPokemonCard() === this) {
              cardList.addBoardEffect(BoardEffect.ABILITY_USED);
            }
          });

          DRAW_CARDS_UNTIL_CARDS_IN_HAND(player, 6);
        }
      });
    }

    // Attack 1: Venomous Fang - poison the opponent's active
    // Ref: set-darkness-ablaze/crobat-v.ts (AFTER_ATTACK + ADD_POISON_TO_PLAYER_ACTIVE)
    if (AFTER_ATTACK(effect, 0, this)) {
      ADD_POISON_TO_PLAYER_ACTIVE(store, state, StateUtils.getOpponent(state, effect.player), this);
    }

    return state;
  }
}
