// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { GameMessage, PlayerType, PowerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED, DAMAGE_OPPONENT_POKEMON } from '../../game/store/prefabs/prefabs';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { GamePhase } from '../../game/store/state/state';
import { ChoosePokemonPrompt } from '../../game/store/prompts/choose-pokemon-prompt';

export class Decidueye extends PokemonCard {
  public stage: Stage = Stage.STAGE_2;
  public evolvesFrom: string = 'Dartrix';
  public cardType: CardType = G;
  public hp: number = 140;
  public weakness = [{ type: R }];
  public retreat = [C, C];

  public powers = [  {
    name: 'Deep Forest Camo',
    powerType: PowerType.ABILITY,
    text: 'Prevent all damage done to this Pokémon by attacks from your opponent\'s Pokémon V and Pokémon-GX.'
  }];

  public attacks = [
    {
      name: 'Splitting Arrow',
      cost: [G, C],
      damage: 90,
      text: 'This attack also does 20 damage to 2 of your opponent\'s Benched Pokémon. (Don\'t apply Weakness and Resistance for Benched Pokémon.)'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV003';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Decidueye';
  public fullName: string = 'Decidueye SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Deep Forest Camo (passive - prevent V/GX damage)
    // Ref: set-darkness-ablaze/decidueye.ts (PutDamageEffect + tag check)
    if (effect instanceof PutDamageEffect && effect.target.cards.includes(this)) {
      const pokemonCard = effect.target.getPokemonCard();
      const sourceCard = effect.source.getPokemonCard();

      if (pokemonCard !== this || sourceCard === undefined) {
        return state;
      }

      // Only block opponent's attacks
      const player = StateUtils.findOwner(state, effect.target);
      const attacker = StateUtils.findOwner(state, effect.source);
      if (player === attacker) {
        return state;
      }

      // Only during attack phase
      if (state.phase !== GamePhase.ATTACK) {
        return state;
      }

      if (sourceCard.tags.includes(CardTag.POKEMON_V) || sourceCard.tags.includes(CardTag.POKEMON_GX)) {
        // Check if ability is blocked
        if (IS_ABILITY_BLOCKED(store, state, player, this)) {
          return state;
        }

        effect.preventDefault = true;
      }
    }

    // Attack 1: Splitting Arrow
    // Ref: set-darkness-ablaze/decidueye.ts (ChoosePokemonPrompt 2 benched + DAMAGE_OPPONENT_POKEMON)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      const benchCount = opponent.bench.filter(b => b.cards.length > 0).length;
      if (benchCount > 0) {
        const max = Math.min(2, benchCount);
        store.prompt(state, new ChoosePokemonPrompt(
          player.id,
          GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
          PlayerType.TOP_PLAYER,
          [SlotType.BENCH],
          { min: max, max: max, allowCancel: false }
        ), selected => {
          const targets = selected || [];
          DAMAGE_OPPONENT_POKEMON(store, state, effect, 20, targets);
        });
      }
    }

    return state;
  }
}
