// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { GamePhase } from '../../game/store/state/state';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class DubwoolV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = C;
  public hp: number = 210;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public powers = [{
    name: 'Soft Wool',
    powerType: PowerType.ABILITY,
    text: 'This Pokémon takes 30 less damage from attacks (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Revenge Blast',
      cost: [C, C, C],
      damage: 120,
      damageCalculation: '+' as '+',
      text: 'This attack does 30 more damage for each Prize card your opponent has taken.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV120';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Dubwool V';
  public fullName: string = 'Dubwool V SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Soft Wool (passive - damage reduction)
    // Ref: set-vivid-voltage/samurott.ts (Swaddling Leaves - DealDamageEffect intercept with GamePhase.ATTACK)
    if (effect instanceof DealDamageEffect
      && effect.target.cards.includes(this)
      && effect.target.getPokemonCard() === this
      && state.phase === GamePhase.ATTACK) {
      const owner = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, owner, this)) {
        return state;
      }

      effect.damage = Math.max(0, effect.damage - 30);
    }

    // Attack 1: Revenge Blast
    // Ref: set-rebel-clash/dubwool-v.ts (Revenge Blast - 30 more damage per opponent prize taken)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      effect.damage += 30 * opponent.prizesTaken;
    }

    return state;
  }
}
