// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class Eiscue extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = W;
  public hp: number = 120;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public powers = [{
    name: 'Ice Face',
    powerType: PowerType.ABILITY,
    text: 'If this Pokémon has full HP, it takes 60 less damage from your opponent\'s attacks (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Blizzard',
      cost: [W, C, C],
      damage: 70,
      text: 'This attack also does 10 damage to each of your opponent\'s Benched Pokémon. (Don\'t apply Weakness and Resistance for Benched Pokémon.)'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV035';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Eiscue';
  public fullName: string = 'Eiscue SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Ice Face (passive - damage reduction when at full HP, after applying W/R)
    // Ref: set-rebel-clash/eiscue.ts (Ice Face - PutDamageEffect intercept with full HP check)
    if (effect instanceof PutDamageEffect
      && effect.target.cards.includes(this)
      && effect.target.getPokemonCard() === this) {
      const owner = StateUtils.findOwner(state, effect.target);

      if (IS_ABILITY_BLOCKED(store, state, owner, this)) {
        return state;
      }

      // Check if this Pokemon has full HP (damage === 0)
      if (effect.target.damage === 0) {
        effect.reduceDamage(60, this.powers[0].name);
      }
    }

    // Attack 1: Blizzard
    // Ref: AGENTS-patterns.md (PutDamageEffect for benched pokemon damage)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      opponent.bench.forEach(benched => {
        if (benched.cards.length > 0) {
          const damage = new PutDamageEffect(effect, 10);
          damage.target = benched;
          store.reduceEffect(state, damage);
        }
      });
    }

    return state;
  }
}
