// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag, SuperType, EnergyType } from '../../game/store/card/card-types';
import { StoreLike, State, StateUtils, GameMessage, PlayerType, SlotType, AttachEnergyPrompt } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { AttachEnergyEffect } from '../../game/store/effects/play-card-effects';

export class EternatusV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 220;
  public weakness = [{ type: F }];
  public retreat = [C, C];

  public attacks = [
    {
      name: 'Power Accelerator',
      cost: [C],
      damage: 30,
      text: 'You may attach a [D] Energy card from your hand to 1 of your Benched Pokémon.'
    },
    {
      name: 'Dynamax Cannon',
      cost: [D, C, C, C],
      damage: 120,
      damageCalculation: '+' as '+',
      text: 'If your opponent\'s Active Pokémon is a Pokémon VMAX, this attack does 120 more damage.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV121';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Eternatus V';
  public fullName: string = 'Eternatus V SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Attack 1: Power Accelerator
    // Ref: set-darkness-ablaze/eternatus-v.ts (Power Accelerator - attach Dark energy to bench)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      return store.prompt(state, new AttachEnergyPrompt(
        player.id,
        GameMessage.ATTACH_ENERGY_CARDS,
        player.hand,
        PlayerType.BOTTOM_PLAYER,
        [SlotType.BENCH],
        { superType: SuperType.ENERGY, energyType: EnergyType.BASIC, name: 'Darkness Energy' },
        { allowCancel: true, min: 0, max: 1 },
      ), transfers => {
        transfers = transfers || [];
        if (transfers.length === 0) {
          return state;
        }
        for (const transfer of transfers) {
          const target = StateUtils.getTarget(state, player, transfer.to);
          const attachEffect = new AttachEnergyEffect(player, transfer.card as any, target);
          store.reduceEffect(state, attachEffect);
        }
      });
    }

    // Attack 2: Dynamax Cannon
    // Ref: set-darkness-ablaze/eternatus-v.ts (Dynamax Cannon - check VMAX tag)
    if (WAS_ATTACK_USED(effect, 1, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (opponent.active.getPokemonCard()?.tags.includes(CardTag.POKEMON_VMAX)) {
        effect.damage += 120;
      }
    }

    return state;
  }
}
