// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, PlayerType, GameError, GameMessage } from '../../game';
import { CheckPokemonTypeEffect, CheckTableStateEffect } from '../../game/store/effects/check-effects';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED } from '../../game/store/prefabs/prefabs';
import { PowerEffect } from '../../game/store/effects/game-effects';

export class EternatusVmax extends PokemonCard {
  public tags = [CardTag.POKEMON_VMAX];
  public stage: Stage = Stage.VMAX;
  public evolvesFrom: string = 'Eternatus V';
  public cardType: CardType = D;
  public hp: number = 340;
  public weakness = [{ type: F }];
  public retreat = [C, C, C];

  public powers = [{
    name: 'Eternal Zone',
    powerType: PowerType.ABILITY,
    text: 'If all of your Pokémon in play are Darkness type, you can have up to 8 Pokémon on your Bench, and you can\'t put non-Darkness Pokémon into play. (If this Ability stops working, discard Pokémon from your Bench until you have 5.)'
  }];

  public attacks = [
    {
      name: 'Dread End',
      cost: [D, C],
      damage: 30,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 30 damage for each of your Darkness Pokémon in play.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV122';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Eternatus VMAX';
  public fullName: string = 'Eternatus VMAX SHF';

  public readonly ETERNATUS_EXPANDED_BENCH = 'ETERNATUS_SHF_EXPANDED_BENCH';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Eternal Zone (expand bench to 8 if all Darkness type, block non-Darkness from entering play)
    // Ref: set-darkness-ablaze/eternatus-vmax.ts (Eternal Zone)
    if (effect instanceof CheckTableStateEffect) {
      effect.benchSizes = state.players.map((player) => {
        try {
          const stub = new PowerEffect(player, {
            name: 'test',
            powerType: PowerType.ABILITY,
            text: ''
          }, this);
          store.reduceEffect(state, stub);
        } catch {
          if (player.marker.hasMarker(this.ETERNATUS_EXPANDED_BENCH, this)) {
            player.marker.removeMarker(this.ETERNATUS_EXPANDED_BENCH, this);
          }
          return 5;
        }

        // Check if Eternatus VMAX is in play for this player
        let isEternInPlay = false;
        player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          const pokemon = cardList.getPokemonCard();
          if (pokemon && pokemon === this) {
            isEternInPlay = true;
          }
        });

        if (!isEternInPlay) {
          if (player.marker.hasMarker(this.ETERNATUS_EXPANDED_BENCH, this)) {
            player.marker.removeMarker(this.ETERNATUS_EXPANDED_BENCH, this);
          }
          return 5;
        }

        // Check each pokemon for dark typing
        let darkPokemon = 0;
        let pokemonInPlay = 1;

        const activeType = new CheckPokemonTypeEffect(player.active);
        store.reduceEffect(state, activeType);
        if (activeType.cardTypes.includes(CardType.DARK)) {
          darkPokemon++;
        }

        player.bench.forEach(benchSpot => {
          if (benchSpot.cards.length > 0) {
            pokemonInPlay++;
            const benchedType = new CheckPokemonTypeEffect(benchSpot);
            store.reduceEffect(state, benchedType);
            if (benchedType.cardTypes.includes(CardType.DARK)) {
              darkPokemon++;
            }
          }
        });

        // If all pokemon in play are dark types
        if (darkPokemon === pokemonInPlay) {
          if (!player.marker.hasMarker(this.ETERNATUS_EXPANDED_BENCH, this)) {
            player.marker.addMarker(this.ETERNATUS_EXPANDED_BENCH, this);
          }
          return 8;
        } else {
          if (player.marker.hasMarker(this.ETERNATUS_EXPANDED_BENCH, this)) {
            player.marker.removeMarker(this.ETERNATUS_EXPANDED_BENCH, this);
          }
          return 5;
        }
      });
    }

    if (effect instanceof PlayPokemonEffect && effect.player.marker.hasMarker(this.ETERNATUS_EXPANDED_BENCH, this)) {
      // Block non-Darkness types from being placed in play
      const checkType = new CheckPokemonTypeEffect(effect.target);
      store.reduceEffect(state, checkType);
      if (!checkType.cardTypes.includes(CardType.DARK)) {
        throw new GameError(GameMessage.BLOCKED_BY_ABILITY);
      }
    }

    // Attack 1: Dread End
    // Ref: set-darkness-ablaze/eternatus-vmax.ts (Dread End - count Darkness Pokemon in play)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      let darksInPlay = 0;

      const activeType = new CheckPokemonTypeEffect(player.active);
      store.reduceEffect(state, activeType);
      if (activeType.cardTypes.includes(CardType.DARK)) {
        darksInPlay++;
      }

      player.bench.forEach(benchSpot => {
        if (benchSpot.cards.length > 0) {
          const benchedType = new CheckPokemonTypeEffect(benchSpot);
          store.reduceEffect(state, benchedType);
          if (benchedType.cardTypes.includes(CardType.DARK)) {
            darksInPlay++;
          }
        }
      });

      effect.damage = 30 * darksInPlay;
    }

    return state;
  }
}
