// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, CardTag } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils } from '../../game';
import { PutDamageEffect } from '../../game/store/effects/attack-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class FalinksV extends PokemonCard {
  public tags = [CardTag.POKEMON_V];
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = F;
  public hp: number = 160;
  public weakness = [{ type: P }];
  public retreat = [C, C];

  public powers = [{
    name: 'Iron Defense Formation',
    powerType: PowerType.ABILITY,
    text: 'All of your Pokémon that have "Falinks" in their name take 20 less damage from your opponent\'s attacks (after applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Giga Impact',
      cost: [F, F, C],
      damage: 210,
      text: 'During your next turn, this Pokémon can\'t attack.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV115';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Falinks V';
  public fullName: string = 'Falinks V SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Iron Defense Formation (passive - Falinks take 20 less damage)
    // Ref: set-rebel-clash/falinks-v.ts (Iron Defense Formation)
    if (effect instanceof PutDamageEffect) {
      const cardList = StateUtils.findCardList(state, this);
      if (!cardList) {
        return state;
      }
      const owner = StateUtils.findOwner(state, cardList);

      if (IS_ABILITY_BLOCKED(store, state, owner, this)) {
        return state;
      }

      const targetPokemon = effect.target.getPokemonCard();
      if (targetPokemon && StateUtils.findOwner(state, effect.target) === owner
        && targetPokemon.name && targetPokemon.name.includes('Falinks')) {
        effect.reduceDamage(20, this.powers[0].name);
      }
    }

    // Attack 1: Giga Impact
    // Ref: AGENTS-patterns.md (cannotAttackNextTurnPending)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      player.active.cannotAttackNextTurnPending = true;
    }

    return state;
  }
}
