// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, PlayerType, SlotType, GameMessage, ChoosePokemonPrompt, ChooseCardsPrompt, Card, PokemonCardList, GameError } from '../../game';
import { EffectOfAbilityEffect } from '../../game/store/effects/game-effects';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, COIN_FLIP_PROMPT, MOVE_CARDS, SHUFFLE_DECK } from '../../game/store/prefabs/prefabs';
import { DiscardCardsEffect } from '../../game/store/effects/attack-effects';

export class Flapple extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Applin';
  public cardType: CardType = G;
  public hp: number = 80;
  public weakness = [{ type: R }];
  public retreat = [C];

  public powers = [{
    name: 'Apple Drop',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, you may put 2 damage counters on 1 of your opponent\'s Pokémon. If you placed any damage counters in this way, shuffle this Pokémon and all attached cards into your deck.'
  }];

  public attacks = [
    {
      name: 'Acid Spray',
      cost: [C, C],
      damage: 60,
      text: 'Flip a coin. If heads, discard an Energy from your opponent\'s Active Pokémon.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV013';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Flapple';
  public fullName: string = 'Flapple SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Apple Drop
    // Ref: set-rebel-clash/flapple.ts (Apple Drop - put 2 counters, then shuffle self into deck)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      return store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
        PlayerType.TOP_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { min: 1, max: 1, allowCancel: false },
      ), selected => {
        const targets = selected || [];

        if (targets.length > 0) {
          const damageEffect = new EffectOfAbilityEffect(player, this.powers[0], this, targets[0]);
          store.reduceEffect(state, damageEffect);
          if (damageEffect.target) {
            damageEffect.target.damage += 20;

            const thisCardList = StateUtils.findCardList(state, this) as PokemonCardList;

            // Shuffle this Pokemon and all attached cards into deck
            const tools = thisCardList.tools.slice();
            tools.forEach(tool => { thisCardList.moveCardTo(tool, player.deck); });

            const pokemons = thisCardList.getPokemons();
            const otherCards = thisCardList.cards.filter(card => !(card instanceof PokemonCard));

            if (otherCards.length > 0) {
              MOVE_CARDS(store, state, thisCardList, player.deck, { cards: otherCards });
            }

            if (pokemons.length > 0) {
              MOVE_CARDS(store, state, thisCardList, player.deck, { cards: pokemons });
            }

            SHUFFLE_DECK(store, state, player);
          }
        }
      });
    }

    // Attack 1: Acid Spray
    // Ref: set-rebel-clash/flapple.ts (Acid Spray - coin flip, if heads discard energy from opponent)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      COIN_FLIP_PROMPT(store, state, player, flipResult => {
        if (flipResult) {
          if (!opponent.active.cards.some(c => c.superType === SuperType.ENERGY)) {
            return;
          }
          let cards: Card[] = [];
          store.prompt(state, new ChooseCardsPrompt(
            player,
            GameMessage.CHOOSE_CARD_TO_DISCARD,
            opponent.active,
            { superType: SuperType.ENERGY },
            { min: 1, max: 1, allowCancel: false }
          ), selected => {
            cards = selected || [];
            const discardEnergy = new DiscardCardsEffect(effect, cards);
            store.reduceEffect(state, discardEnergy);
          });
        }
      });
    }

    return state;
  }
}
