// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { ChoosePokemonPrompt, GameMessage, PlayerType, PowerType, SlotType, StoreLike, State, StateUtils } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PlaceDamageCountersEffect } from '../../game/store/effects/game-effects';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';
import { WAS_ATTACK_USED, IS_ABILITY_BLOCKED, COIN_FLIP_PROMPT } from '../../game/store/prefabs/prefabs';

export class GalarianZigzagoon extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = D;
  public hp: number = 70;
  public weakness = [{ type: G }];
  public retreat = [C];

  public powers = [  {
    name: 'Headbutt Tantrum',
    powerType: PowerType.ABILITY,
    text: 'When you play this Pokémon from your hand onto your Bench during your turn, you may put 1 damage counter on 1 of your opponent\'s Pokémon.'
  }];

  public attacks = [
    {
      name: 'Surprise Attack',
      cost: [D, C],
      damage: 30,
      text: 'Flip a coin. If tails, this attack does nothing.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV078';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Zigzagoon';
  public fullName: string = 'Galarian Zigzagoon SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Headbutt Tantrum
    // Ref: set-sword-and-shield/galarian-zigzagoon.ts (Headbutt Tantrum - PlayPokemonEffect, damage counter)
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = StateUtils.findOwner(state, effect.target);
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      const hasTargets = opponent.bench.some(b => b.cards.length > 0) || opponent.active.cards.length > 0;
      if (!hasTargets) {
        return state;
      }

      store.prompt(state, new ChoosePokemonPrompt(
        player.id,
        GameMessage.CHOOSE_POKEMON_TO_DAMAGE,
        PlayerType.TOP_PLAYER,
        [SlotType.ACTIVE, SlotType.BENCH],
        { min: 1, max: 1, allowCancel: true }
      ), selected => {
        if (!selected || selected.length === 0) {
          return;
        }

        const target = selected[0];
        const damageEffect = new PlaceDamageCountersEffect(player, target, 10);
        store.reduceEffect(state, damageEffect);
      });
    }

    // Attack 1: Surprise Attack
    // Ref: AGENTS-patterns.md (flip coin, if tails attack does nothing)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      COIN_FLIP_PROMPT(store, state, player, result => {
        if (!result) {
          effect.damage = 0;
        }
      });
    }

    return state;
  }
}
