// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType } from '../../game/store/card/card-types';
import { PlayerType, PowerType, StoreLike, State, StateUtils } from '../../game';
import { DealDamageEffect } from '../../game/store/effects/attack-effects';
import { CheckPokemonTypeEffect } from '../../game/store/effects/check-effects';
import { Effect } from '../../game/store/effects/effect';
import { IS_ABILITY_BLOCKED } from '../../game/store/prefabs/prefabs';

export class GalarianPerrserker extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Galarian Meowth';
  public cardType: CardType = M;
  public hp: number = 120;
  public weakness = [{ type: R }];
  public resistance = [{ type: G, value: -30 }];
  public retreat = [C, C];

  public powers = [{
    name: 'Steely Spirit',
    powerType: PowerType.ABILITY,
    text: 'Your Metal Pokémon\'s attacks do 20 more damage to your opponent\'s Active Pokémon (before applying Weakness and Resistance).'
  }];

  public attacks = [
    {
      name: 'Metal Claw',
      cost: [M, M, C],
      damage: 70,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV087';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Perrserker';
  public fullName: string = 'Galarian Perrserker SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Steely Spirit (passive - Metal Pokemon's attacks do 20 more damage)
    // Ref: set-sword-and-shield/galarian-perrserker.ts (Steely Spirit - DealDamageEffect intercept)
    if (effect instanceof DealDamageEffect) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        return state;
      }

      const hasPerrserkerInPlay = player.bench.some(b => b.cards.includes(this)) || player.active.cards.includes(this);
      let numberOfPerrserkersInPlay = 0;

      if (hasPerrserkerInPlay) {
        player.forEachPokemon(PlayerType.BOTTOM_PLAYER, (cardList) => {
          if (cardList.cards.includes(this)) {
            numberOfPerrserkersInPlay++;
          }
        });
      }

      // Check if attacker is a Metal Pokemon
      const checkPokemonTypeEffect = new CheckPokemonTypeEffect(player.active);
      store.reduceEffect(state, checkPokemonTypeEffect);

      if (checkPokemonTypeEffect.cardTypes.includes(CardType.METAL) && effect.target === opponent.active) {
        effect.damage += 20 * numberOfPerrserkersInPlay;
      }
    }

    return state;
  }
}
