// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, SuperType, BoardEffect } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, GameError, GameMessage, ChooseCardsPrompt, ShowCardsPrompt, ShuffleDeckPrompt, PlayerType, Card } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { PowerEffect } from '../../game/store/effects/game-effects';
import { PlayPokemonEffect } from '../../game/store/effects/play-card-effects';
import { EndTurnEffect } from '../../game/store/effects/game-phase-effects';

export class GalarianMeowth extends PokemonCard {
  public stage: Stage = Stage.BASIC;
  public cardType: CardType = M;
  public hp: number = 60;
  public weakness = [{ type: R }];
  public resistance = [{ type: G, value: -30 }];
  public retreat = [C, C];

  public powers = [{
    name: 'Evolution Roar',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'You must discard 2 cards from your hand in order to use this Ability. Once during your turn, you may search your deck for a Galarian Perrserker, reveal it, and put it into your hand. Then, shuffle your deck.'
  }];

  public attacks = [
    {
      name: 'Scratch',
      cost: [M, C],
      damage: 20,
      text: ''
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV086';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Meowth';
  public fullName: string = 'Galarian Meowth SHF';

  public readonly EVOLUTION_ROAR_MARKER = 'EVOLUTION_ROAR_MARKER_SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Clear marker when this Pokemon is played
    if (effect instanceof PlayPokemonEffect && effect.pokemonCard === this) {
      const player = effect.player;
      player.marker.removeMarker(this.EVOLUTION_ROAR_MARKER, this);
    }

    // Clear marker at end of turn
    if (effect instanceof EndTurnEffect) {
      const player = effect.player;
      player.marker.removeMarker(this.EVOLUTION_ROAR_MARKER, this);
    }

    // Ability: Evolution Roar
    // Ref: set-rebel-clash/galarian-meowth.ts (Evolution Roar - discard 2 from hand + search deck for Galarian Perrserker)
    if (effect instanceof PowerEffect && effect.power === this.powers[0]) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (player.marker.hasMarker(this.EVOLUTION_ROAR_MARKER, this)) {
        throw new GameError(GameMessage.POWER_ALREADY_USED);
      }

      if (player.hand.cards.length < 2) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      if (player.deck.cards.length === 0) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      let cards: Card[] = [];

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_DISCARD,
        player.hand,
        {},
        { min: 2, max: 2, allowCancel: false }
      ), selected => {
        cards = selected || [];
        player.hand.moveCardsTo(cards, player.discard);

        store.prompt(state, new ChooseCardsPrompt(
          player,
          GameMessage.CHOOSE_CARD_TO_HAND,
          player.deck,
          { superType: SuperType.POKEMON, name: 'Galarian Perrserker' },
          { min: 1, max: 1, allowCancel: true }
        ), selected2 => {
          const perrserkersFound = selected2 || [];
          player.deck.moveCardsTo(perrserkersFound, player.hand);

          if (perrserkersFound.length > 0) {
            store.prompt(state, new ShowCardsPrompt(
              opponent.id,
              GameMessage.CARDS_SHOWED_BY_THE_OPPONENT,
              perrserkersFound
            ), () => state);
          }
        });

        player.marker.addMarker(this.EVOLUTION_ROAR_MARKER, this);

        player.forEachPokemon(PlayerType.BOTTOM_PLAYER, cardList => {
          if (cardList.getPokemonCard() === this) {
            cardList.addBoardEffect(BoardEffect.ABILITY_USED);
          }
        });

        return store.prompt(state, new ShuffleDeckPrompt(player.id), order => {
          player.deck.applyOrder(order);
        });
      });
    }

    return state;
  }
}
