// This file was auto-generated by the card stub generator.
// Card effects were implemented by an agent.
// If you have any questions or feedback, reach out to @C4 in the discord.

import { PokemonCard } from '../../game/store/card/pokemon-card';
import { Stage, CardType, BoardEffect } from '../../game/store/card/card-types';
import { PowerType, StoreLike, State, StateUtils, ChooseCardsPrompt, GameError, GameMessage, CardList, PlayerType } from '../../game';
import { Effect } from '../../game/store/effects/effect';
import { WAS_ATTACK_USED, WAS_POWER_USED, IS_ABILITY_BLOCKED, USE_ABILITY_ONCE_PER_TURN, REMOVE_MARKER_AT_END_OF_TURN } from '../../game/store/prefabs/prefabs';

export class GalarianMrRime extends PokemonCard {
  public stage: Stage = Stage.STAGE_1;
  public evolvesFrom: string = 'Galarian Mr. Mime';
  public cardType: CardType = W;
  public hp: number = 120;
  public weakness = [{ type: M }];
  public retreat = [C, C];

  public powers = [{
    name: 'Shuffle Dance',
    useWhenInPlay: true,
    powerType: PowerType.ABILITY,
    text: 'Once during your turn, you may switch 1 of your opponent\'s face-down Prize cards with the top card of their deck. (The cards stay face down.)'
  }];

  public attacks = [
    {
      name: 'Mad Party',
      cost: [W, C, C],
      damage: 20,
      damageCalculation: 'x' as 'x',
      text: 'This attack does 20 damage for each Pokémon in your discard pile that has the Mad Party attack.'
    }
  ];

  public regulationMark: string = 'D';
  public set: string = 'SHF';
  public setNumber: string = 'SV021';
  public cardImage: string = 'assets/cardback.png';
  public name: string = 'Galarian Mr. Rime';
  public fullName: string = 'Galarian Mr. Rime SHF';

  public readonly SHUFFLE_DANCE_MARKER = 'SHUFFLE_DANCE_MARKER_SHF';

  public reduceEffect(store: StoreLike, state: State, effect: Effect): State {
    // Ability: Shuffle Dance
    // Ref: set-darkness-ablaze/galarian-mr-rime.ts (Shuffle Dance - switch prize with top deck card)
    if (WAS_POWER_USED(effect, 0, this)) {
      const player = effect.player;
      const opponent = StateUtils.getOpponent(state, player);

      if (IS_ABILITY_BLOCKED(store, state, player, this)) {
        throw new GameError(GameMessage.BLOCKED_BY_EFFECT);
      }

      USE_ABILITY_ONCE_PER_TURN(player, this.SHUFFLE_DANCE_MARKER, this);

      const prizes = opponent.prizes.filter(p => p.isSecret);

      if (prizes.length === 0) {
        throw new GameError(GameMessage.CANNOT_PLAY_THIS_CARD);
      }

      const originallyFaceDown = opponent.prizes.map(p => p.isSecret);

      // Make prizes accessible for selection
      prizes.forEach(p => { p.isSecret = true; });

      const allPrizeCards = new CardList();
      allPrizeCards.isSecret = true;
      prizes.forEach(prizeList => {
        allPrizeCards.cards.push(...prizeList.cards);
      });

      store.prompt(state, new ChooseCardsPrompt(
        player,
        GameMessage.CHOOSE_CARD_TO_HAND,
        allPrizeCards,
        {},
        { min: 1, max: 1, allowCancel: false, isSecret: true }
      ), chosenPrize => {
        const prizeCard = chosenPrize[0];
        const deck = opponent.deck;

        const temp = new CardList();
        deck.moveTo(temp, 1);

        // Find the prize list containing the chosen card
        const chosenPrizeList = opponent.prizes.find(prizeList => prizeList.cards.includes(prizeCard));

        if (chosenPrizeList) {
          const temp2 = new CardList();
          chosenPrizeList.moveCardTo(prizeCard, temp2);
          temp2.moveToTopOfDestination(deck);
          temp.moveTo(chosenPrizeList, 1);
        }

        // Restore face-down state
        opponent.prizes.forEach((p, index) => {
          if (originallyFaceDown[index]) {
            p.isSecret = true;
          }
        });

        // Mark ability as used
        player.forEachPokemon(PlayerType.BOTTOM_PLAYER, cardList => {
          if (cardList.getPokemonCard() === this) {
            cardList.addBoardEffect(BoardEffect.ABILITY_USED);
          }
        });

        return state;
      });
    }

    REMOVE_MARKER_AT_END_OF_TURN(effect, this.SHUFFLE_DANCE_MARKER, this);

    // Attack 1: Mad Party
    // Ref: set-darkness-ablaze/galarian-mr-rime.ts (Mad Party - count Pokemon in discard with Mad Party attack)
    if (WAS_ATTACK_USED(effect, 0, this)) {
      const player = effect.player;

      let pokemonCount = 0;
      player.discard.cards.forEach(c => {
        if (c instanceof PokemonCard && c.attacks.some(a => a.name === 'Mad Party')) {
          pokemonCount += 1;
        }
      });

      effect.damage = pokemonCount * 20;
    }

    return state;
  }
}
